### ISSUE TITLE
Fail if projects-excludes not set

### ISSUE THREAD

**Issue by freeseacher** [messagebird/gcppromd#12]
I'm launching gcppromd with that line
`./gcppromd-0.3.0.linux-amd64 -outputPath /etc/prometheus/gcppromd_v1_gce_instances.json -projects "sre-team-dev-tf" -daemon`
i really do not want autodiscovery here and only want that project to be used. 
but command fails with 
```
INFO[0000] Running as a daemon, output is going to be written to /etc/prometheus/gcppromd_v1_gce_instances.json 
INFO[0000] Targets update frequency: 300 seconds        
INFO[0000] Projects Auto-Discovery: false               
INFO[0000] Targets projects: [sre-team-dev-tf]           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6d042f]

goroutine 1 [running]:
regexp.(*Regexp).String(...)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/regexp/regexp.go:106
main.main()
	/Users/felix/Projects/github.com/messagebird/gcppromd/cmd/gcppromd/main.go:93 +0x63f
```

tmp workaround is to set 
`-projects-excludes '^$'` 
Should be pretty simple to fix as i can see

**Comment by freeseacher** [comment]
up
